/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.suslsport.sportmgtsystem.ThirdPartyFn.ComboSearch;
import org.suslsport.sportmgtsystem.controller.CurrentStockContrller;
import org.suslsport.sportmgtsystem.controller.InventoryController;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.OnHandQuantityContrller;
import org.suslsport.sportmgtsystem.model.CurrentStock;
import org.suslsport.sportmgtsystem.model.OnHandQuantity;
import sun.java2d.pipe.DrawImage;

/**
 *
 * @author RedHunter
 */
public class AddCurrentStock extends javax.swing.JPanel {
    Main aThis = null;

    /**
     * Creates new form AddCurrentStock
     */
     String stockId=null;
     int quan=0;
     int newQuantity =0;
    public AddCurrentStock(Main aThis) {
        try {
            initComponents();
            this.aThis = aThis;
            
            
            
            
            ComboSearch comboSearch = new ComboSearch();
            
            
            ArrayList<String> allVoucherId = InventoryController.getAllVoucherId();
            jCombo_Voucher_id.addItem("Select Voucher");
            jComboBox_ItemName.addItem("Select Item Name");
            for (String string : allVoucherId) {
                jCombo_Voucher_id.addItem(string);
            }
         
            
            comboSearch.setSearchableCombo(jCombo_Voucher_id, true, "");
            loadDataToItem();
           
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCurrentStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCurrentStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    
public void loadDataToItem() throws ClassNotFoundException, SQLException{
    ComboSearch comboSearch1 = new ComboSearch();
    jComboBox_ItemName.removeAllItems();
    ArrayList<String> allItemName = ItemController.getAllItemName();
            for (String string : allItemName) {
                jComboBox_ItemName.addItem(string);
                
            }
     comboSearch1.setSearchableCombo(jComboBox_ItemName, true, "");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText_quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_Add_Inventory = new javax.swing.JButton();
        jCombo_Voucher_id = new javax.swing.JComboBox<>();
        jComboBox_ItemName = new javax.swing.JComboBox<>();
        jLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Voucher Id                              :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Item Name                              :");

        jText_quantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Quantity                                 :");

        jButton_Add_Inventory.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Add_Inventory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_Inventory.setText("Add Stock");
        jButton_Add_Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_InventoryActionPerformed(evt);
            }
        });

        jCombo_Voucher_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCombo_Voucher_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCombo_Voucher_idFocusLost(evt);
            }
        });
        jCombo_Voucher_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_Voucher_idActionPerformed(evt);
            }
        });

        jComboBox_ItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ItemNameActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setText("Add Current Stock");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(6, 6, 6)
                            .addComponent(jText_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jCombo_Voucher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(6, 6, 6)
                            .addComponent(jComboBox_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox_ItemName, jCombo_Voucher_id, jText_quantity});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_Voucher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton_Add_Inventory});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Add_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_InventoryActionPerformed
        try {
            // TODO add your handling code here:
            
            String voucherId =jCombo_Voucher_id.getSelectedItem().toString();
            String itemName = jComboBox_ItemName.getSelectedItem().toString();
            String relevantItemId = ItemController.getRelevantItemId(itemName);
            stockId=voucherId+""+relevantItemId;
            
            
           
            String quantity =jText_quantity.getText();
            int q =Integer.parseInt(quantity);
            System.out.println(q);
            
            
            boolean checkAddRow = OnHandQuantityContrller.checkAddRow(relevantItemId);
             
            if(checkAddRow){
                ResultSet checkRow = OnHandQuantityContrller.checkRow(relevantItemId);
                if(checkRow.last()){
                    String s = checkRow.getString(2);
                    newQuantity= Integer.parseInt(s);
                    System.out.println(newQuantity);
                    quan = q+newQuantity;
                    System.out.println(quan);
                    OnHandQuantity handQ=new OnHandQuantity(relevantItemId, quan);
                    boolean updateRow = OnHandQuantityContrller.updateRow(handQ);
                    
                }else{
                    
                }
                
                 
            }else{
                OnHandQuantity handQuanad=new OnHandQuantity(relevantItemId, q);
                
                OnHandQuantityContrller.addRow(handQuanad);
            }
            
            
            CurrentStock cs = new CurrentStock(stockId, voucherId, relevantItemId,q);
            boolean addCurrentStock = CurrentStockContrller.addCurrentStock(cs);
            if(addCurrentStock){
                //loadDataToItem();
                jText_quantity.setText("");
                JOptionPane.showMessageDialog(this, "Stock added successfully");
            }else{
                JOptionPane.showMessageDialog(this, "Error in adding stock");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCurrentStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddCurrentStock.class.getName()).log(Level.SEVERE, null, ex);
        }
 

    }//GEN-LAST:event_jButton_Add_InventoryActionPerformed

    private void jCombo_Voucher_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_Voucher_idActionPerformed
       
        
    }//GEN-LAST:event_jCombo_Voucher_idActionPerformed

    private void jComboBox_ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ItemNameActionPerformed
        
        
        
    }//GEN-LAST:event_jComboBox_ItemNameActionPerformed

    private void jCombo_Voucher_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCombo_Voucher_idFocusLost
        
       
    }//GEN-LAST:event_jCombo_Voucher_idFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        aThis.getjPanel_Manage_Inventory().setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Add_Inventory;
    private javax.swing.JComboBox<String> jComboBox_ItemName;
    private javax.swing.JComboBox<String> jCombo_Voucher_id;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jText_quantity;
    // End of variables declaration//GEN-END:variables

    
}
