/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.SportController;
import org.suslsport.sportmgtsystem.model.Items;

/**
 *
 * @author RedHunter
 */

public class AddItemsView extends javax.swing.JPanel {
    Main aThis = null;

    /**
     * Creates new form AddItemsView
     */
    public AddItemsView(Main aThis)  {
        initComponents();
        this.aThis = aThis;
        jText_ItemId.setEnabled(false);
        try {
            loadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
  
    }
    public void loadData() throws ClassNotFoundException, SQLException{
          
            ArrayList<String> allSportsNames = SportController.getAllSportsNames();
            for (String sportName :allSportsNames ) {
            jCombo_SportNames.addItem(sportName);
            
        }
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jText_ItemId = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_ItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCombo_SportNames = new javax.swing.JComboBox<>();
        jButton_AddItems = new javax.swing.JButton();
        jButton_AddItems1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Item Id                                 :");

        jText_ItemId.setEditable(false);
        jText_ItemId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setText("Add Items");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Item Name                            :");

        jText_ItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Relevant Sport                      :");

        jCombo_SportNames.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCombo_SportNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_SportNamesActionPerformed(evt);
            }
        });

        jButton_AddItems.setBackground(new java.awt.Color(0, 153, 255));
        jButton_AddItems.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AddItems.setText("Add Item");
        jButton_AddItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddItemsActionPerformed(evt);
            }
        });

        jButton_AddItems1.setBackground(new java.awt.Color(0, 153, 255));
        jButton_AddItems1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AddItems1.setText("Cancel");
        jButton_AddItems1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddItems1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jCombo_SportNames, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jText_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jText_ItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_AddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_AddItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCombo_SportNames, jText_ItemId, jText_ItemName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_SportNames, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_ItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddItems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AddItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCombo_SportNames, jText_ItemId, jText_ItemName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4});

    }// </editor-fold>//GEN-END:initComponents

    private void jCombo_SportNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_SportNamesActionPerformed
        // TODO add your handling code here:
        String sportName = jCombo_SportNames.getSelectedItem().toString();
        String relevantSportId=null;
        try {
            relevantSportId = SportController.getRelevantSportId(sportName);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String lastId = ItemController.getLastId(relevantSportId);
            jText_ItemId.setText(lastId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jCombo_SportNamesActionPerformed

    private void jButton_AddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddItemsActionPerformed
        // TODO add your handling code here:
        String itemId = jText_ItemId.getText();
        String itemName = jText_ItemName.getText();
        
        String sportName =jCombo_SportNames.getSelectedItem().toString();
       
        
        try {
            String relevantSportId = SportController.getRelevantSportId(sportName);
            
            Items item=new Items(itemId, itemName, relevantSportId);
            boolean addItemsRes = ItemController.addItems(item);
            if (addItemsRes) {
                
                //JOptionPane.showMessageDialog(this, "Item added successfully");
                loadData();
                jText_ItemName.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Error in adding item");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemsView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_AddItemsActionPerformed

    private void jButton_AddItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddItems1ActionPerformed
        // TODO add your handling code here:
         aThis.getjPanel_Manage_Sport_Eq().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AddItems1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddItems;
    private javax.swing.JButton jButton_AddItems1;
    private javax.swing.JComboBox<String> jCombo_SportNames;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jText_ItemId;
    private javax.swing.JTextField jText_ItemName;
    // End of variables declaration//GEN-END:variables
}
