/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.suslsport.sportmgtsystem.ThirdPartyFn.OnlyStringAndWhiteSpace;
import org.suslsport.sportmgtsystem.controller.InventoryController;
import org.suslsport.sportmgtsystem.model.Inventory;

/**
 *
 * @author RedHunter
 */
public class AddInventory extends javax.swing.JPanel {
Main aThis = null;
AddCurrentStock acs =null;
    /**
     * Creates new form AddInventory
     */
    public AddInventory(Main aThis) {
        initComponents();
        this.aThis = aThis;
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        jText_date.setText(dateFormat.format(cal.getTime()));
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jText_voucher_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jText_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jText_from_whome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Add_Inventory = new javax.swing.JButton();
        jLabel_errorMessage = new javax.swing.JLabel();
        jButton_Add_Inventory_cancel = new javax.swing.JButton();

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setText("Add Inventory");

        jText_voucher_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jText_voucher_id.setToolTipText("Enter a Voucher Number");
        jText_voucher_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_voucher_idKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_voucher_idKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Voucher Id                              :");

        jText_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jText_date.setToolTipText("Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date                                       :");

        jText_from_whome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jText_from_whome.setToolTipText("Where this voucher from ");
        jText_from_whome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_from_whomeKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("From Whome                           :");

        jButton_Add_Inventory.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Add_Inventory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_Inventory.setText("Add Inventory");
        jButton_Add_Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_InventoryActionPerformed(evt);
            }
        });

        jLabel_errorMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        jButton_Add_Inventory_cancel.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Add_Inventory_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_Inventory_cancel.setText("Cancel");
        jButton_Add_Inventory_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Inventory_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_Inventory_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jText_voucher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_date, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_from_whome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Add_Inventory_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_errorMessage, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap(418, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jText_date, jText_from_whome, jText_voucher_id});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_voucher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_from_whome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addComponent(jLabel_errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add_Inventory_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jText_date, jText_from_whome, jText_voucher_id});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Add_Inventory, jButton_Add_Inventory_cancel});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Add_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_InventoryActionPerformed
        // TODO add your handling code here:
        String vId = jText_voucher_id.getText();
        String date =jText_date.getText();
        String fWhom =jText_from_whome.getText();
        Inventory  inventory =new Inventory(vId, date, fWhom);
        
        if (!vId.equals("")&& !date.equals("")&&!fWhom.equals("")) {
               try {
            boolean addInventory = InventoryController.addInventory(inventory);
                   if (addInventory) {
                       jText_voucher_id.setText("");
                       jText_from_whome.setText("");
                       if (acs == null) {
                           acs = new AddCurrentStock(aThis);
                           aThis.getjPanel_center().add(acs);
                           acs.setSize(1360, 595);         
                           acs.setVisible(true);
                           this.setVisible(false);
                           
                       }else{
                           aThis.getjPanel_center().add(acs);
                           acs.setSize(1360, 595);         
                           acs.setVisible(true);
                           this.setVisible(false);
                       
                       }
                       //JOptionPane.showMessageDialog(this, "Voucher is successfully added");
            }else{
                JOptionPane.showMessageDialog(this, "Error in adding voucher");
            }
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(AddInventory.class.getName()).log(Level.SEVERE, null, ex);
                   System.out.println("Error 1");
        } catch (SQLException ex) {
            //Logger.getLogger(AddInventory.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, "Incorrect Data");
        }
        }else{
            JOptionPane.showMessageDialog(this, "Please fill the all fields");
        }
        
        

    
    }//GEN-LAST:event_jButton_Add_InventoryActionPerformed

    private void jButton_Add_Inventory_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_Inventory_cancelActionPerformed
        // TODO add your handling code here:
        aThis.getjPanel_Manage_Inventory().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton_Add_Inventory_cancelActionPerformed

    private void jText_voucher_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_voucher_idKeyPressed
        // TODO add your handling code here:
        setNumericOnly(jText_voucher_id);

    }//GEN-LAST:event_jText_voucher_idKeyPressed

    private void jText_voucher_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_voucher_idKeyTyped
        // TODO add your handling code here:
        checkCharacter(jText_voucher_id);
        
    }//GEN-LAST:event_jText_voucher_idKeyTyped

    private void jText_from_whomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_from_whomeKeyPressed
        // TODO add your handling code here:
        OnlyStringAndWhiteSpace.setOnlyStringAndWhiteSpace(jText_from_whome);
    }//GEN-LAST:event_jText_from_whomeKeyPressed

public static void checkCharacter(JTextField jTextField){
    
jTextField.addKeyListener(new KeyAdapter() {
    public void keyTyped(KeyEvent e) { 
        if (jTextField.getText().length() >= 4 ) // limit textfield to 3 characters
            e.consume(); 
    }  
});
         }

  public static void setNumericOnly(JTextField jTextField){
    jTextField.addKeyListener(new KeyAdapter() {
         public void keyTyped(KeyEvent e) {
           char c = e.getKeyChar();
           
           if ((!Character.isDigit(c) ||
              (c == KeyEvent.VK_BACK_SPACE) ||
              (c == KeyEvent.VK_DELETE))) {
                e.consume();
              }
         }
    });
} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Inventory;
    private javax.swing.JButton jButton_Add_Inventory_cancel;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_errorMessage;
    private javax.swing.JTextField jText_date;
    private javax.swing.JTextField jText_from_whome;
    private javax.swing.JTextField jText_voucher_id;
    // End of variables declaration//GEN-END:variables
}
