/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.OutFromStockController;
import org.suslsport.sportmgtsystem.model.OutFromStock;

/**
 *
 * @author RedHunter
 */
public class AllOutThreds extends javax.swing.JPanel {
Main aThis = null;
    /**
     * Creates new form AllOutThreds
     */
    public AllOutThreds(Main aThis) {
        initComponents();
        this.aThis = aThis;
        try {
            DefaultTableModel  dtm = (DefaultTableModel) jTable_allOutTrheds.getModel();
            
            ArrayList<OutFromStock> viewAllOutThreds = OutFromStockController.viewAllOutThreds();
            
            for (OutFromStock viewAllOutThred : viewAllOutThreds) {
                boolean outType = viewAllOutThred.isOutType();
                Object [] b = {viewAllOutThred.getDate(),viewAllOutThred.getStudentId(),viewAllOutThred.getContact(),ItemController.getReleventItemName(viewAllOutThred.getItemId()),viewAllOutThred.getQuantity(),viewAllOutThred.getOutedBy()};
                if (outType) {
                    dtm.addRow(b);
                    jTable_allOutTrheds.setGridColor(Color.red);
                    
                }else{
                    dtm.addRow(b);
                }
                    
                 
            }
        } catch (SQLException ex) {
            Logger.getLogger(AllOutThreds.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllOutThreds.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 
 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_allOutTrheds = new javax.swing.JTable();
        jButton_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable_allOutTrheds.setAutoCreateRowSorter(true);
        jTable_allOutTrheds.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_allOutTrheds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Student Reg No", "Contact No", "Item Name", "Quantity", "Outed By"
            }
        ));
        jTable_allOutTrheds.setRowHeight(20);
        jScrollPane1.setViewportView(jTable_allOutTrheds);

        jButton_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("All Invoices ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
      aThis.getjPanel_Invoices().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_allOutTrheds;
    // End of variables declaration//GEN-END:variables
}
