/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.suslsport.sportmgtsystem.ThirdPartyFn.ComboSearch;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.OnHandQuantityContrller;
import org.suslsport.sportmgtsystem.controller.SportController;
import org.suslsport.sportmgtsystem.model.OnHandQuantity;
import org.suslsport.sportmgtsystem.model.Sport;

/**
 *
 * @author RedHunter
 */
public class AllOnHandViewAccordingToSports extends javax.swing.JPanel {
    Main aThis=null;

    /**
     * Creates new form AllOnHandViewAccordingToSports
     */
    public AllOnHandViewAccordingToSports(Main aThis){
        
            initComponents();
            this.aThis=aThis;
            ComboSearch comboSearch=new ComboSearch();
        ArrayList<Sport> viewAllSports;
        try {
            viewAllSports = SportController.viewAllSports();
             jComboBox_AllSportNames.addItem("Select Sport");
        for (Sport viewAllSport : viewAllSports) {
            jComboBox_AllSportNames.addItem(viewAllSport.getSportName());
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        }
       
            
        
            
            comboSearch.setSearchableCombo(jComboBox_AllSportNames, true, TOOL_TIP_TEXT_KEY);
      
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_AllSportNames = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ViewItemsAccordingToSports = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        jComboBox_AllSportNames.setToolTipText("Select a Sport to view Equipments");
        jComboBox_AllSportNames.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox_AllSportNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AllSportNamesActionPerformed(evt);
            }
        });

        jTable_ViewItemsAccordingToSports.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_ViewItemsAccordingToSports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Available Quantity"
            }
        ));
        jTable_ViewItemsAccordingToSports.setRowHeight(20);
        jScrollPane1.setViewportView(jTable_ViewItemsAccordingToSports);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("According to Sport");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox_AllSportNames, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_AllSportNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_AllSportNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AllSportNamesActionPerformed
        // TODO add your handling code here:
     if(jComboBox_AllSportNames.getSelectedIndex() > 0){
            String relevantSportId = null;
        DefaultTableModel dtm = (DefaultTableModel) jTable_ViewItemsAccordingToSports.getModel();
        dtm.setRowCount(0);
        String sName = (String) jComboBox_AllSportNames.getSelectedItem();
        try {
             relevantSportId= SportController.getRelevantSportId(sName);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ArrayList<OnHandQuantity> itemsRelevantToSports = OnHandQuantityContrller.getItemsRelevantToSports(relevantSportId);
            for (OnHandQuantity itemsRelevantToSport : itemsRelevantToSports) {
                String relevantItemName= ItemController.getReleventItemName(itemsRelevantToSport.getItemId());
                Object[] b ={relevantItemName,itemsRelevantToSport.getQuantity()};
                dtm.addRow(b);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AllOnHandViewAccordingToSports.class.getName()).log(Level.SEVERE, null, ex);
        }
     }else{
//         JOptionPane.showMessageDialog(null,"You must selsect a Sport","Warning",JOptionPane.WARNING_MESSAGE);
     }
       
    }//GEN-LAST:event_jComboBox_AllSportNamesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_AllSportNames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_ViewItemsAccordingToSports;
    // End of variables declaration//GEN-END:variables
}
