/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.image.Image;
import static javafx.scene.input.KeyCode.G;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static jdk.nashorn.internal.runtime.regexp.joni.Syntax.Java;
import org.suslsport.sportmgtsystem.ThirdPartyFn.ImageTest;
import org.suslsport.sportmgtsystem.controller.SystemUserController;
import org.suslsport.sportmgtsystem.model.SystemUsers;
import smart_sport.RunSmartSport;

/**
 *
 * @author RedHunter
 */
public class LoginPanel extends javax.swing.JPanel {

    Main aThis = null;
    SystemUsers systemUsers = null;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(Main aThis) {
        initComponents();
        this.aThis = aThis;
        ImageIcon icon = new ImageIcon("G:\\Java Learning\\Smart_Sport\\src\\images\\ji.png");
        ImageTest.setImage(this, icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_loginpanel_uname = new javax.swing.JTextField();
        jPasswordField_loginpanel_password = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jLabel_error = new javax.swing.JLabel();

        setLayout(null);

        jTextField_loginpanel_uname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_loginpanel_uname.setBorder(null);
        jTextField_loginpanel_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_loginpanel_unameActionPerformed(evt);
            }
        });
        add(jTextField_loginpanel_uname);
        jTextField_loginpanel_uname.setBounds(900, 320, 370, 40);

        jPasswordField_loginpanel_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_loginpanel_password.setBorder(null);
        jPasswordField_loginpanel_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_loginpanel_passwordActionPerformed(evt);
            }
        });
        jPasswordField_loginpanel_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_loginpanel_passwordKeyTyped(evt);
            }
        });
        add(jPasswordField_loginpanel_password);
        jPasswordField_loginpanel_password.setBounds(900, 390, 370, 40);

        jButton_login.setBackground(new java.awt.Color(76, 76, 76));
        jButton_login.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        add(jButton_login);
        jButton_login.setBounds(880, 480, 420, 50);

        jLabel_error.setBackground(new java.awt.Color(51, 51, 255));
        jLabel_error.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(255, 0, 51));
        add(jLabel_error);
        jLabel_error.setBounds(870, 450, 300, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_loginpanel_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_loginpanel_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_loginpanel_passwordActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
String uName=null;
         uName= jTextField_loginpanel_uname.getText();
char[] password =null;
       password = jPasswordField_loginpanel_password.getPassword();
       int length=0;
         length= password.length;
        if (!uName.equals("") && length > 0) {
            String pass=null;
            pass = jPasswordField_loginpanel_password.getText();

            if (systemUsers == null) {
                systemUsers = new SystemUsers(uName, pass);
            }

            try {
                //System.out.println(uName);
               // System.out.println(pass);

                boolean checkUser = SystemUserController.checkUser(systemUsers);

                //System.out.println(checkUser);
                if (checkUser) {
                    if (uName.equals("admin")) {
                         aThis.getjButton_logout().setVisible(true);

                        aThis.getjLabel_username_view().setText("User : [" + uName+"]");
                        JPanel jPanel_center = aThis.getjPanel_center();
                        jPanel_center.setSize(1360, 610);
                        
                        JPanel jPanel_mainButton = aThis.getjPanel_mainButton();
                        jPanel_mainButton.setSize(1360, 610);
                        ImageIcon icon = new ImageIcon("G:\\Java Learning\\Smart_Sport\\src\\images\\front button.jpg");
                        ImageTest.setImage(jPanel_mainButton, icon);
                        jPanel_center.add(jPanel_mainButton);
                        jPanel_mainButton.setVisible(true);

                        jPanel_center.setVisible(true);
                        this.setVisible(false);
                    } else {
                        
                    aThis.getjButton_logout().setVisible(true);

                        aThis.getjLabel_username_view().setText("User : [" + uName+"]");
                        JPanel jPanel_center = aThis.getjPanel_center();
                        jPanel_center.setSize(1360, 610);
                        
                        JPanel jPanel_mainButton = aThis.getjPanel_mainButton();
                        jPanel_mainButton.setSize(1360, 610);
                        aThis.getjLabel_username_view().setVisible(true);
                        aThis.getjButton_main_System_users().setEnabled(false);
                        ImageIcon icon = new ImageIcon("G:\\Java Learning\\Smart_Sport\\src\\images\\front button.jpg");
                        ImageTest.setImage(jPanel_mainButton, icon);
                        jPanel_center.add(jPanel_mainButton);
                        jPanel_mainButton.setVisible(true);

                        jPanel_center.setVisible(true);
                        this.setVisible(false);
                    }
                    //System.out.println("ok");

                } else {
                    jLabel_error.setText("*Incorrect username or password");
                    jTextField_loginpanel_uname.setText("");
                    jPasswordField_loginpanel_password.setText("");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            jLabel_error.setText("*Please fill the all fields");

        }

    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jTextField_loginpanel_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_loginpanel_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_loginpanel_unameActionPerformed

    private void jPasswordField_loginpanel_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_loginpanel_passwordKeyTyped
        // TODO add your handling code here:
        checkCharacter(jPasswordField_loginpanel_password);
    }//GEN-LAST:event_jPasswordField_loginpanel_passwordKeyTyped
    public static void checkCharacter(JTextField jTextField) {

        jTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (jTextField.getText().length() >= 9) // limit textfield to 3 characters
                {
                    e.consume();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JPasswordField jPasswordField_loginpanel_password;
    private javax.swing.JTextField jTextField_loginpanel_uname;
    // End of variables declaration//GEN-END:variables
}
