/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.JButton;

/**
 *
 * @author RedHunter
 */
public class Main extends javax.swing.JPanel {
    
    SystemUserView systemUserView =null;
    SystemUser systemUser =null;
    AllSportView  allSportView =null;
    AddSportView  addSportView = null;
    AllItemVIew allItemVIew = null;
    AddItemsView addItemsView = null;
    AllVoucher allVoucher = null;
    AddInventory  addInventory =null;
    NeedToReturnInvoices needToReturn =null;
    OutFromStockView outFromStockView = null;
    AllOutThreds allOutThreds = null;
    AddOnHandQuantity addOnHandQuantity =null;
    OnHandItemView  handItemView =null;
     AllOnHandViewAccordingToSports accordingToSports =null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
//        jPanel_top.setSize(1360, 50);
//        jPanel_center.setSize(1360, 550);
//        jPanel_bottom.setSize(1360,20);
//        
//        
//        
//        jPanel_top.setLocation(0, 0);
//        this.add(jPanel_top);
//        jPanel_top.setVisible(true);
//        
//        jPanel_center.setLocation(0,55);
//        
//        this.add(jPanel_center);
//        jPanel_center.setVisible(true);
//        
//        jPanel_bottom.setLocation(0, 0);
//        this.add(jPanel_bottom);
//        jPanel_bottom.setVisible(true);
//        
       jPanel_center.add(jPanel_mainButton);
       jPanel_center.setVisible(true);
       
        
       jPanel_mainButton.setSize(1360,610);
       jPanel_mainButton.setVisible(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_mainButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton_Onhand_quantity = new javax.swing.JButton();
        jButton_manageInventory = new javax.swing.JButton();
        jButton_main_Invoices = new javax.swing.JButton();
        jButton_main_manage_eq = new javax.swing.JButton();
        jButton_main_manage_sport = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel_Invoices = new javax.swing.JPanel();
        jButton_back_I = new javax.swing.JButton();
        jButton_allInvoices = new javax.swing.JButton();
        jButton_needToReturn = new javax.swing.JButton();
        jPanel_onhandQuantity = new javax.swing.JPanel();
        jButton_addOnHandItem = new javax.swing.JButton();
        jButton_AllOnHandQuantity = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanel_Manage_Inventory = new javax.swing.JPanel();
        jButton_Add_Inventory = new javax.swing.JButton();
        jButton_View_Inventory = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel_Manage_Sport_Eq = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton_add_new_equ = new javax.swing.JButton();
        jButton_view_all_equ = new javax.swing.JButton();
        jPanel_Manage_Sport = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton_add_sport = new javax.swing.JButton();
        jButton_View_all_sport = new javax.swing.JButton();
        jPanel_Sys_user = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton_add_new_user = new javax.swing.JButton();
        jButton_All_user = new javax.swing.JButton();
        jPanel_top = new javax.swing.JPanel();
        jPanel_center = new javax.swing.JPanel();

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Out Sport Equipments");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_Onhand_quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Onhand_quantity.setText("On Hand Stock");
        jButton_Onhand_quantity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Onhand_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Onhand_quantityActionPerformed(evt);
            }
        });

        jButton_manageInventory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_manageInventory.setText("Manage Inventory");
        jButton_manageInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_manageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manageInventoryActionPerformed(evt);
            }
        });

        jButton_main_Invoices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_main_Invoices.setText("Invoices");
        jButton_main_Invoices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_main_Invoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_InvoicesActionPerformed(evt);
            }
        });

        jButton_main_manage_eq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_main_manage_eq.setText("Manage Sport Equipments");
        jButton_main_manage_eq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_main_manage_eq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_manage_eqActionPerformed(evt);
            }
        });

        jButton_main_manage_sport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_main_manage_sport.setText("Manage Sport");
        jButton_main_manage_sport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_main_manage_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_manage_sportActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("System Users");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_mainButtonLayout = new javax.swing.GroupLayout(jPanel_mainButton);
        jPanel_mainButton.setLayout(jPanel_mainButtonLayout);
        jPanel_mainButtonLayout.setHorizontalGroup(
            jPanel_mainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainButtonLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel_mainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainButtonLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_main_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainButtonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Onhand_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_manageInventory)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_main_manage_eq)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_main_manage_sport, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel_mainButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton7, jButton_Onhand_quantity, jButton_main_manage_eq, jButton_main_manage_sport, jButton_manageInventory});

        jPanel_mainButtonLayout.setVerticalGroup(
            jPanel_mainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainButtonLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel_mainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_main_Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel_mainButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Onhand_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_manageInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_main_manage_eq)
                    .addComponent(jButton_main_manage_sport)
                    .addComponent(jButton7))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel_mainButtonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton7, jButton_Onhand_quantity, jButton_main_manage_eq, jButton_main_manage_sport, jButton_manageInventory});

        jButton_back_I.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_back_I.setText("Back");
        jButton_back_I.setBorder(null);
        jButton_back_I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_back_IActionPerformed(evt);
            }
        });

        jButton_allInvoices.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_allInvoices.setText("All Invoices");
        jButton_allInvoices.setBorder(null);
        jButton_allInvoices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_allInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_allInvoicesActionPerformed(evt);
            }
        });

        jButton_needToReturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_needToReturn.setText("Need To Return");
        jButton_needToReturn.setBorder(null);
        jButton_needToReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_needToReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_needToReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InvoicesLayout = new javax.swing.GroupLayout(jPanel_Invoices);
        jPanel_Invoices.setLayout(jPanel_InvoicesLayout);
        jPanel_InvoicesLayout.setHorizontalGroup(
            jPanel_InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InvoicesLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jButton_allInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton_needToReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(jPanel_InvoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_back_I, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_InvoicesLayout.setVerticalGroup(
            jPanel_InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InvoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_back_I, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_InvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_needToReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_allInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel_onhandQuantity.setPreferredSize(new java.awt.Dimension(1360, 610));

        jButton_addOnHandItem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_addOnHandItem.setText("Add On Hand Items");
        jButton_addOnHandItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_addOnHandItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addOnHandItemActionPerformed(evt);
            }
        });

        jButton_AllOnHandQuantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_AllOnHandQuantity.setText("All On Hand Quantity");
        jButton_AllOnHandQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AllOnHandQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AllOnHandQuantityActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_onhandQuantityLayout = new javax.swing.GroupLayout(jPanel_onhandQuantity);
        jPanel_onhandQuantity.setLayout(jPanel_onhandQuantityLayout);
        jPanel_onhandQuantityLayout.setHorizontalGroup(
            jPanel_onhandQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_onhandQuantityLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jButton_addOnHandItem, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton_AllOnHandQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(jPanel_onhandQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_onhandQuantityLayout.setVerticalGroup(
            jPanel_onhandQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_onhandQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_onhandQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addOnHandItem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AllOnHandQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel_Manage_Inventory.setPreferredSize(new java.awt.Dimension(1360, 610));

        jButton_Add_Inventory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Add_Inventory.setText("Add Voucher");
        jButton_Add_Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_InventoryActionPerformed(evt);
            }
        });

        jButton_View_Inventory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_View_Inventory.setText("All Received Voucher");
        jButton_View_Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_View_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_InventoryActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Back");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Manage_InventoryLayout = new javax.swing.GroupLayout(jPanel_Manage_Inventory);
        jPanel_Manage_Inventory.setLayout(jPanel_Manage_InventoryLayout);
        jPanel_Manage_InventoryLayout.setHorizontalGroup(
            jPanel_Manage_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_InventoryLayout.createSequentialGroup()
                .addGroup(jPanel_Manage_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Manage_InventoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Manage_InventoryLayout.createSequentialGroup()
                        .addContainerGap(180, Short.MAX_VALUE)
                        .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton_View_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 180, Short.MAX_VALUE))
        );
        jPanel_Manage_InventoryLayout.setVerticalGroup(
            jPanel_Manage_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_InventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_Manage_InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_View_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel_Manage_Sport_Eq.setPreferredSize(new java.awt.Dimension(1360, 610));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_add_new_equ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_add_new_equ.setText("Add New Equipments");
        jButton_add_new_equ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add_new_equ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_new_equActionPerformed(evt);
            }
        });

        jButton_view_all_equ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_view_all_equ.setText("View All Equpments");
        jButton_view_all_equ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_view_all_equ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_view_all_equActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Manage_Sport_EqLayout = new javax.swing.GroupLayout(jPanel_Manage_Sport_Eq);
        jPanel_Manage_Sport_Eq.setLayout(jPanel_Manage_Sport_EqLayout);
        jPanel_Manage_Sport_EqLayout.setHorizontalGroup(
            jPanel_Manage_Sport_EqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_Sport_EqLayout.createSequentialGroup()
                .addGroup(jPanel_Manage_Sport_EqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Manage_Sport_EqLayout.createSequentialGroup()
                        .addContainerGap(180, Short.MAX_VALUE)
                        .addComponent(jButton_add_new_equ, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton_view_all_equ, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Manage_Sport_EqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel_Manage_Sport_EqLayout.setVerticalGroup(
            jPanel_Manage_Sport_EqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_Sport_EqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_Manage_Sport_EqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_view_all_equ, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton_add_new_equ, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel_Manage_Sport.setPreferredSize(new java.awt.Dimension(1360, 610));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_add_sport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_add_sport.setText("Add New Sport");
        jButton_add_sport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_sportActionPerformed(evt);
            }
        });

        jButton_View_all_sport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_View_all_sport.setText("View All Sports");
        jButton_View_all_sport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_View_all_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_all_sportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Manage_SportLayout = new javax.swing.GroupLayout(jPanel_Manage_Sport);
        jPanel_Manage_Sport.setLayout(jPanel_Manage_SportLayout);
        jPanel_Manage_SportLayout.setHorizontalGroup(
            jPanel_Manage_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_SportLayout.createSequentialGroup()
                .addGroup(jPanel_Manage_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Manage_SportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Manage_SportLayout.createSequentialGroup()
                        .addContainerGap(180, Short.MAX_VALUE)
                        .addComponent(jButton_add_sport, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton_View_all_sport, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel_Manage_SportLayout.setVerticalGroup(
            jPanel_Manage_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Manage_SportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_Manage_SportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_View_all_sport, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton_add_sport, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel_Sys_user.setPreferredSize(new java.awt.Dimension(1360, 610));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton_add_new_user.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_add_new_user.setText("Add New System User");
        jButton_add_new_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_new_userActionPerformed(evt);
            }
        });

        jButton_All_user.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_All_user.setText("View All Users");
        jButton_All_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_All_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_All_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Sys_userLayout = new javax.swing.GroupLayout(jPanel_Sys_user);
        jPanel_Sys_user.setLayout(jPanel_Sys_userLayout);
        jPanel_Sys_userLayout.setHorizontalGroup(
            jPanel_Sys_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Sys_userLayout.createSequentialGroup()
                .addGroup(jPanel_Sys_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Sys_userLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton_add_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton_All_user, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Sys_userLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel_Sys_userLayout.setVerticalGroup(
            jPanel_Sys_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Sys_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel_Sys_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add_new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_All_user, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1360, 680));
        setPreferredSize(new java.awt.Dimension(1360, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel_topLayout = new javax.swing.GroupLayout(jPanel_top);
        jPanel_top.setLayout(jPanel_topLayout);
        jPanel_topLayout.setHorizontalGroup(
            jPanel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_topLayout.setVerticalGroup(
            jPanel_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 40));

        javax.swing.GroupLayout jPanel_centerLayout = new javax.swing.GroupLayout(jPanel_center);
        jPanel_center.setLayout(jPanel_centerLayout);
        jPanel_centerLayout.setHorizontalGroup(
            jPanel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_centerLayout.setVerticalGroup(
            jPanel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel_center, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1360, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_main_manage_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_manage_sportActionPerformed
        // TODO add your handling code here:
        getjPanel_Manage_Sport().setSize(1360, 610);
        getjPanel_center().add(getjPanel_Manage_Sport());
        getjPanel_Manage_Sport().setVisible(true);
        getjPanel_mainButton().setVisible(false);
    }//GEN-LAST:event_jButton_main_manage_sportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(null==outFromStockView){
            outFromStockView = new OutFromStockView(this);
        }
        outFromStockView.setSize(1360, 610);
        outFromStockView.setLocation(0, 0);
       
        getjPanel_center().add(outFromStockView);
        outFromStockView.setVisible(true);
        getjPanel_mainButton().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_main_InvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_InvoicesActionPerformed
        // TODO add your handling code here:
        getjPanel_Invoices().setSize(1360, 610);
        getjPanel_center().add(getjPanel_Invoices());
        getjPanel_Invoices().setVisible(true);
        getjPanel_mainButton().setVisible(false);
        
        
    }//GEN-LAST:event_jButton_main_InvoicesActionPerformed

    private void jButton_back_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_back_IActionPerformed
        // TODO add your handling code here:
        
        jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_Invoices.setVisible(false);
    }//GEN-LAST:event_jButton_back_IActionPerformed

    private void jButton_allInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_allInvoicesActionPerformed
        // TODO add your handling code here:
        if(allOutThreds==null){
            allOutThreds = new AllOutThreds(this);
        }
        allOutThreds.setSize(1360, 610);
        getjPanel_center().add(allOutThreds);
        allOutThreds.setVisible(true);
        getjPanel_Invoices().setVisible(false);
        
       
        
    }//GEN-LAST:event_jButton_allInvoicesActionPerformed

    private void jButton_manageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manageInventoryActionPerformed
        // TODO add your handling code here:
        getjPanel_center().add(getjPanel_Manage_Inventory());
        getjPanel_Manage_Inventory().setSize(1360, 610);
        getjPanel_Manage_Inventory().setVisible(true);
        getjPanel_mainButton().setVisible(false);
        
    }//GEN-LAST:event_jButton_manageInventoryActionPerformed

    private void jButton_Onhand_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Onhand_quantityActionPerformed
        // TODO add your handling code here:
        getjPanel_center().add(getjPanel_onhandQuantity());
        getjPanel_onhandQuantity().setSize(1360, 610);
        getjPanel_onhandQuantity().setVisible(true);
        getjPanel_mainButton().setVisible(false);
    }//GEN-LAST:event_jButton_Onhand_quantityActionPerformed

    private void jButton_addOnHandItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addOnHandItemActionPerformed
        // TODO add your handling code here:
        if(addOnHandQuantity==null){
            addOnHandQuantity = new AddOnHandQuantity(this);
        }
        addOnHandQuantity.setSize(1360, 610);
        getjPanel_center().add(addOnHandQuantity);
        addOnHandQuantity.setVisible(true);
        getjPanel_onhandQuantity().setVisible(false);
    }//GEN-LAST:event_jButton_addOnHandItemActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
       jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_onhandQuantity.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButton_AllOnHandQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AllOnHandQuantityActionPerformed
        // TODO add your handling code here:
        if(handItemView==null) {
            handItemView = new OnHandItemView(this);
        }
        if(accordingToSports==null){
             accordingToSports = new AllOnHandViewAccordingToSports(this);
        }
        handItemView.setSize(680, 610);
        accordingToSports.setSize(680, 610);
        getjPanel_center().add(handItemView);
        handItemView.setLocation(0, 0);
        accordingToSports.setLocation(680, 0);
        getjPanel_center().add(accordingToSports);
        accordingToSports.setVisible(true);
        handItemView.setVisible(true);
        getjPanel_onhandQuantity().setVisible(false);
    }//GEN-LAST:event_jButton_AllOnHandQuantityActionPerformed

    private void jButton_needToReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_needToReturnActionPerformed
        // TODO add your handling code here:
        if(null==needToReturn){
             needToReturn = new NeedToReturnInvoices(this);
         }
        needToReturn.setSize(1360,610);
        needToReturn.setLocation(0, 0);
        getjPanel_center().add(needToReturn);
        needToReturn.setVisible(true);
        getjPanel_Invoices().setVisible(false);
        
    }//GEN-LAST:event_jButton_needToReturnActionPerformed

    private void jButton_Add_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_InventoryActionPerformed
        // TODO add your handling code here:
        if(null==addInventory){
             addInventory = new AddInventory(this);
         }
        addInventory.setSize(1360,610);
        addInventory.setLocation(0, 0);
        getjPanel_center().add(addInventory);
        addInventory.setVisible(true);
        getjPanel_Manage_Inventory().setVisible(false);
    }//GEN-LAST:event_jButton_Add_InventoryActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_Manage_Inventory.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton_View_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_InventoryActionPerformed
        // TODO add your handling code here:
          if(null==allVoucher){
             allVoucher = new AllVoucher(this);
         }
        allVoucher.setSize(1360,610);
        allVoucher.setLocation(0, 0);
        getjPanel_center().add(allVoucher);
        allVoucher.setVisible(true);
        getjPanel_Manage_Inventory().setVisible(false);
    }//GEN-LAST:event_jButton_View_InventoryActionPerformed

    private void jButton_main_manage_eqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_manage_eqActionPerformed
        // TODO add your handling code here:
         getjPanel_Manage_Sport_Eq().setSize(1360, 610);
        getjPanel_center().add(getjPanel_Manage_Sport_Eq());
        getjPanel_Manage_Sport_Eq().setVisible(true);
        getjPanel_mainButton().setVisible(false);
    }//GEN-LAST:event_jButton_main_manage_eqActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_Manage_Sport_Eq.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_add_new_equActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_new_equActionPerformed
        // TODO add your handling code here:
        if(addItemsView==null){
            addItemsView = new AddItemsView(this);
        }
        addItemsView.setSize(1360, 610);
        getjPanel_center().add(addItemsView);
        addItemsView.setVisible(true);
        getjPanel_Manage_Sport_Eq().setVisible(false);
    }//GEN-LAST:event_jButton_add_new_equActionPerformed

    private void jButton_view_all_equActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_view_all_equActionPerformed
        // TODO add your handling code here:
        if(allItemVIew==null){
            allItemVIew = new AllItemVIew(this);
        }
        allItemVIew.printData();
        allItemVIew.setSize(1360, 610);
        getjPanel_center().add(allItemVIew);
        allItemVIew.setVisible(true);
        getjPanel_Manage_Sport_Eq().setVisible(false);
    }//GEN-LAST:event_jButton_view_all_equActionPerformed

    private void jButton_add_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_sportActionPerformed
        // TODO add your handling code here:
        if(addSportView==null){
            addSportView = new AddSportView(this);
        }
        addSportView.setSize(1360, 610);
        getjPanel_center().add(addSportView);
        addSportView.setVisible(true);
        getjPanel_Manage_Sport().setVisible(false);
    }//GEN-LAST:event_jButton_add_sportActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_Manage_Sport.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_View_all_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_all_sportActionPerformed
        // TODO add your handling code here:
        if(allSportView==null){
            allSportView = new AllSportView(this);
        }
        allSportView.printData();
        allSportView.setSize(1360, 610);
        getjPanel_center().add(allSportView);
        allSportView.setVisible(true);
        getjPanel_Manage_Sport().setVisible(false);
    }//GEN-LAST:event_jButton_View_all_sportActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        getjPanel_Sys_user().setSize(1360, 610);
        getjPanel_center().add(getjPanel_Sys_user());
        getjPanel_Sys_user().setVisible(true);
        getjPanel_mainButton().setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         jPanel_mainButton.setSize(1360, 610);
        jPanel_mainButton.setVisible(true);
        jPanel_Sys_user.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_add_new_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_new_userActionPerformed
        // TODO add your handling code here:
        if(systemUser==null){
            systemUser = new SystemUser(this);
        }
        systemUser.setSize(1360, 610);
        getjPanel_center().add(systemUser);
        systemUser.setVisible(true);
        getjPanel_Sys_user().setVisible(false);
    }//GEN-LAST:event_jButton_add_new_userActionPerformed

    private void jButton_All_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_All_userActionPerformed
        // TODO add your handling code here:
        
        if(systemUserView==null){
            systemUserView = new SystemUserView(this);
        }
        systemUserView.setSize(1360, 610);
        getjPanel_center().add(systemUserView);
        systemUserView.setVisible(true);
        getjPanel_Sys_user().setVisible(false);
    }//GEN-LAST:event_jButton_All_userActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButton_Add_Inventory;
    private javax.swing.JButton jButton_AllOnHandQuantity;
    private javax.swing.JButton jButton_All_user;
    private javax.swing.JButton jButton_Onhand_quantity;
    private javax.swing.JButton jButton_View_Inventory;
    private javax.swing.JButton jButton_View_all_sport;
    private javax.swing.JButton jButton_addOnHandItem;
    private javax.swing.JButton jButton_add_new_equ;
    private javax.swing.JButton jButton_add_new_user;
    private javax.swing.JButton jButton_add_sport;
    private javax.swing.JButton jButton_allInvoices;
    private javax.swing.JButton jButton_back_I;
    private javax.swing.JButton jButton_main_Invoices;
    private javax.swing.JButton jButton_main_manage_eq;
    private javax.swing.JButton jButton_main_manage_sport;
    private javax.swing.JButton jButton_manageInventory;
    private javax.swing.JButton jButton_needToReturn;
    private javax.swing.JButton jButton_view_all_equ;
    private javax.swing.JPanel jPanel_Invoices;
    private javax.swing.JPanel jPanel_Manage_Inventory;
    private javax.swing.JPanel jPanel_Manage_Sport;
    private javax.swing.JPanel jPanel_Manage_Sport_Eq;
    private javax.swing.JPanel jPanel_Sys_user;
    private javax.swing.JPanel jPanel_center;
    private javax.swing.JPanel jPanel_mainButton;
    private javax.swing.JPanel jPanel_onhandQuantity;
    private javax.swing.JPanel jPanel_top;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanel_onhandQuantity
     */
    public javax.swing.JPanel getjPanel_onhandQuantity() {
        return jPanel_onhandQuantity;
    }

    /**
     * @return the jPanel_center
     */
    public javax.swing.JPanel getjPanel_center() {
        return jPanel_center;
    }

    /**
     * @return the jPanel_mainButton
     */
    public javax.swing.JPanel getjPanel_mainButton() {
        return jPanel_mainButton;
    }

    /**
     * @return the jPanel_Invoices
     */
    public javax.swing.JPanel getjPanel_Invoices() {
        return jPanel_Invoices;
    }

    /**
     * @return the jPanel_Manage_Inventory
     */
    public javax.swing.JPanel getjPanel_Manage_Inventory() {
        return jPanel_Manage_Inventory;
    }

    /**
     * @return the jPanel_Manage_Sport_Eq
     */
    public javax.swing.JPanel getjPanel_Manage_Sport_Eq() {
        return jPanel_Manage_Sport_Eq;
    }

    /**
     * @return the jPanel_Manage_Sport
     */
    public javax.swing.JPanel getjPanel_Manage_Sport() {
        return jPanel_Manage_Sport;
    }

    /**
     * @return the jPanel_Sys_user
     */
    public javax.swing.JPanel getjPanel_Sys_user() {
        return jPanel_Sys_user;
    }
}
