/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.OnHandQuantityContrller;
import org.suslsport.sportmgtsystem.model.OnHandQuantity;

/**
 *
 * @author RedHunter
 */
public class OnHandItemView extends javax.swing.JPanel {
    Main aThis=null;

    /**
     * Creates new form OnHandItemView
     */
    public OnHandItemView(Main aThis)  {
        try {
            initComponents();
            this.aThis = aThis;
            printData();
        } catch (SQLException ex) {
            Logger.getLogger(OnHandItemView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OnHandItemView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ViewAllOnHandQuantity = new javax.swing.JTable();
        jButton_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable_ViewAllOnHandQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_ViewAllOnHandQuantity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity"
            }
        ));
        jTable_ViewAllOnHandQuantity.setRowHeight(20);
        jScrollPane1.setViewportView(jTable_ViewAllOnHandQuantity);

        jButton_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_back.setText("Back");
        jButton_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("All On Hand Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(760, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        aThis.getjPanel_onhandQuantity().setVisible(true);
        this.setVisible(false);
        
        aThis.accordingToSports.setVisible(false);
        
        
        
        
        
        
    }//GEN-LAST:event_jButton_backActionPerformed

public void printData() throws SQLException, ClassNotFoundException{
    DefaultTableModel model =(DefaultTableModel) jTable_ViewAllOnHandQuantity.getModel();
    model.setRowCount(0);
        ArrayList<OnHandQuantity> viewAllItems = OnHandQuantityContrller.viewAllItems();
        for (OnHandQuantity viewAllItem : viewAllItems) {
            
        String releventItemName = ItemController.getReleventItemName(viewAllItem.getItemId());
            Object[] onHand={releventItemName,viewAllItem.getQuantity()};
            model.addRow(onHand);
    }
   
    
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ViewAllOnHandQuantity;
    // End of variables declaration//GEN-END:variables
}
