/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.suslsport.sportmgtsystem.view;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.suslsport.sportmgtsystem.ThirdPartyFn.ComboSearch;
import org.suslsport.sportmgtsystem.controller.ItemController;
import org.suslsport.sportmgtsystem.controller.OnHandQuantityContrller;
import org.suslsport.sportmgtsystem.controller.OutFromStockController;
import org.suslsport.sportmgtsystem.controller.SystemUserController;
import org.suslsport.sportmgtsystem.model.OnHandQuantity;
import org.suslsport.sportmgtsystem.model.OutFromStock;
import org.suslsport.sportmgtsystem.model.SystemUsers;

/**
 *
 * @author RedHunter
 */
public class OutFromStockView extends javax.swing.JPanel {
    int selectedRow ;
    Main aThis=null;
    
    /**
     * Creates new form OutFromStock
     */
    public OutFromStockView(Main aThis){
        initComponents();
        this.aThis = aThis;
        
        
        getDate();
        addItemToCombo();
        
        try {
            addUserNameToCombo();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

   

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton_yes_Confirm = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Available_q = new javax.swing.JTextField();
        jComboBox_Item_Name = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField_out_quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_item_list = new javax.swing.JTable();
        jButton_del = new javax.swing.JButton();
        jTextField_contact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_reg_no = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox_return_type = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_select_Outed_by = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton_yes_Confirm.setText("Yes,Out this list and FINISH");
        jButton_yes_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_yes_ConfirmActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton_yes_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_yes_Confirm)
                    .addComponent(jButton_cancel))
                .addGap(36, 36, 36))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel1.setText("Date :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jTextField_date.setEditable(false);
        add(jTextField_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 180, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setText("Student Registation No :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel3.setText("Item Name   :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jTextField_Available_q.setEditable(false);
        jTextField_Available_q.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTextField_Available_q.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Available_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Available_qActionPerformed(evt);
            }
        });
        add(jTextField_Available_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 120, 100));

        jComboBox_Item_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Item_NameActionPerformed(evt);
            }
        });
        add(jComboBox_Item_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 440, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel4.setText("Available Quantity :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 140, 20));
        add(jTextField_out_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 440, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel5.setText("Out quantity :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1330, 10));

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setText("Add to List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 590, 40));

        jTable_item_list.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jTable_item_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity"
            }
        ));
        jTable_item_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_item_listMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable_item_listMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_item_list);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 520, 200));

        jButton_del.setText("Delete");
        jButton_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delActionPerformed(evt);
            }
        });
        add(jButton_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 120, 70, 50));

        jTextField_contact.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        add(jTextField_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 181, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel10.setText("Contact No :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jTextField_reg_no.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        add(jTextField_reg_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 181, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Out From Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 730, 50));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel8.setText("Return Type :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 90, 20));

        jCheckBox_return_type.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jCheckBox_return_type.setSelected(true);
        jCheckBox_return_type.setText("Need Return");
        add(jCheckBox_return_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel9.setText("Outed By :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        add(jComboBox_select_Outed_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 430, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 10, 620));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 1330, 20));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 480, 50));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel6.setText("Out Items :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBox_Item_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Item_NameActionPerformed
        // TODO add your handling code here:
        String itemName = jComboBox_Item_Name.getSelectedItem().toString();
        try {
            String relevantItemId = ItemController.getRelevantItemId(itemName);
            int relevantQuantity = OnHandQuantityContrller.getRelevantQuantity(relevantItemId);
            String sRelevantQuantity = Integer.toString(relevantQuantity);
            jTextField_Available_q.setText(sRelevantQuantity);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jComboBox_Item_NameActionPerformed

    private void jTextField_Available_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Available_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Available_qActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String itemName = jComboBox_Item_Name.getSelectedItem().toString();
        
        String outQuantiy =jTextField_out_quantity.getText();
        DefaultTableModel dtm = (DefaultTableModel) jTable_item_list.getModel();
        Object[] itemx = {itemName,outQuantiy};
        dtm.addRow(itemx);
        jTextField_out_quantity.setText(null);
        jTextField_Available_q.setText(null);
        jComboBox_Item_Name.setSelectedIndex(0);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_item_listMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_item_listMouseReleased
       
        
    }//GEN-LAST:event_jTable_item_listMouseReleased

    private void jTable_item_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_item_listMouseClicked
        // TODO add your handling code here:
        selectedRow = jTable_item_list.getSelectedRow();
        
    }//GEN-LAST:event_jTable_item_listMouseClicked

    private void jButton_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable_item_list.getModel();
        model.removeRow(selectedRow);
    }//GEN-LAST:event_jButton_delActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jDialog1.setSize(500, 300);
        jDialog1.add(jPanel1);
        jPanel1.setLocation(50, 50);
        jDialog1.pack();
        jDialog1.setVisible(true);
        jDialog1.setLocation(50, 50);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_yes_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_yes_ConfirmActionPerformed
        // TODO add your handling code here:
        
        String d = jTextField_date.getText();
        String stId = jTextField_reg_no.getText();
        String contactNo =jTextField_contact.getText();
        String itemName ;
       
        
        DefaultTableModel model = (DefaultTableModel) jTable_item_list.getModel();
        int rowCount = model.getRowCount();
        ArrayList<OnHandQuantity> al = new ArrayList<>();
        OnHandQuantity handQuantity ;
        for (int i = 0; i < rowCount; i++) {
            
            
            try {
                itemName = model.getValueAt(i,0).toString();
                String relevantItemId = ItemController.getRelevantItemId(itemName);
                //System.out.println(itemName);
                String quantity = model.getValueAt(i,1).toString();
                
                handQuantity =new OnHandQuantity(relevantItemId, Integer.parseInt(quantity));
                OnHandQuantityContrller.updateRowOuting(handQuantity);
                
                
                
                boolean selectedReturn = jCheckBox_return_type.isSelected();
                System.out.println(selectedReturn);
                
                String outedBy = jComboBox_select_Outed_by.getSelectedItem().toString();
                OutFromStock fromStock = new OutFromStock(d,stId,contactNo,relevantItemId,Integer.parseInt(quantity),selectedReturn,outedBy);
                
                boolean add = OutFromStockController.add(fromStock);
                if (add) {
                   // jDialog1.setVisible(false);
                    JOptionPane.showMessageDialog(jButton1, "Successfull");
                }else{
                    JOptionPane.showMessageDialog(jButton1, "Fail");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
       
        
    }//GEN-LAST:event_jButton_yes_ConfirmActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      //jPanel_center.setVisible(true);
      aThis.getjPanel_mainButton().setVisible(true);
      this.setVisible(false);
     
        
                
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void getDate(){
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        jTextField_date.setText(dateFormat.format(cal.getTime()));
}
    public void addUserNameToCombo() throws ClassNotFoundException, SQLException{
        ComboSearch comboS = new ComboSearch();
        comboS.setSearchableCombo(jComboBox_select_Outed_by, true, TOOL_TIP_TEXT_KEY);
        ArrayList<SystemUsers> all = SystemUserController.getAll();
        
        for (SystemUsers systemUsers : all) {
            jComboBox_select_Outed_by.addItem(systemUsers.getFullName());
        }
        
    }
    public void addItemToCombo(){
    ComboSearch comboSearch = new ComboSearch();
        try {
            ArrayList<OnHandQuantity> viewAllItems = OnHandQuantityContrller.viewAllItems();
            
            //jComboBox_Item_Name.addItem("Select Item");
            for (OnHandQuantity viewAllItem : viewAllItems) {
                String releventItemName = ItemController.getReleventItemName(viewAllItem.getItemId());
                jComboBox_Item_Name.addItem(releventItemName);
                
            }
             comboSearch.setSearchableCombo(jComboBox_Item_Name, true, TOOL_TIP_TEXT_KEY);
        } catch (SQLException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OutFromStockView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_del;
    private javax.swing.JButton jButton_yes_Confirm;
    private javax.swing.JCheckBox jCheckBox_return_type;
    private javax.swing.JComboBox<String> jComboBox_Item_Name;
    private javax.swing.JComboBox<String> jComboBox_select_Outed_by;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_item_list;
    private javax.swing.JTextField jTextField_Available_q;
    private javax.swing.JTextField jTextField_contact;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_out_quantity;
    private javax.swing.JTextField jTextField_reg_no;
    // End of variables declaration//GEN-END:variables
}
